<?php echo $this->doctype(); ?>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" ng-controller="BaseCtrl" lang="en" ng-app="NotesApp"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" ng-controller="BaseCtrl" lang="en" ng-app="NotesApp"> <![endif]-->
<!--[if IE 8]>    <html xmlns:ng="http://angularjs.org" id="ng-app" ng-app="NotesApp" class="no-js lt-ie9"  ng-controller="BaseCtrl" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="no-js" ng-app="NotesApp" ng-controller="BaseCtrl" detect-ie10> <!--<![endif]-->

<html lang="en">
    <head>
        <meta charset="utf-8">
        <base href="/">
        <?php echo $this->headTitle($this->translate('Notes Application'))->setSeparator(' - ')->setAutoEscape(false) ?>


        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'))
            ->prependStylesheet($this->basePath() . '/css/vendor.min.css')
            ->prependStylesheet($this->basePath() . '/css/app.css')
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css');
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/vendor.min.js')
        ; ?>

    </head>
    <body>
        <div ui-view>
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript()
            ->offsetSetFile(1, $this->basePath() . '/js/app.min.js');
        ?>
    </body>
</html>
